### ISSUE TITLE
Execute a record

### ISSUE THREAD

**Issue by yolloz** [MichalKyjovsky/nswi153#37]
When accessing an execution endpoint `POST /api/execution/5/`, I get this error:
```
"POST /api/execution/5/ HTTP/1.1" 500 93656
Internal Server Error: /api/execution/5/
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
TypeError: start_execution() got an unexpected keyword argument 'record'
```

**Comment by bodommer** [comment]
Should be fixed when 'start_execution()' endpoint is implemented - see branch 18-integrate-celery-to-the-solution. @MichalKyjovsky
